### PR TITLE
Milestone: Friendships v2

### PR DESCRIPTION
**Pull request by keddo**
- Added all the required features.

Kindly asking for review!!

### CODE REVIEW

**Review by maelfosso — CHANGES_REQUESTED** [review]
# Changes required :red_circle: 

Hello,

Thank you for the well-done job so far
It's working like a charm

However, there is some error that needs to be fixed

0. Please, follow this [link](https://github.com/microverseinc/linters-config/tree/master/ror) to Set-up GitHub Actions in your repository and **please, use the same `rubocop.yml` that the one of this repository**

1. Rspec generate this error
```rb
An error occurred while loading ./spec/controllers/friendship_controller_spec.rb.
Failure/Error:
  RSpec.describe FriendshipController, type: :controller do
  end

NameError:
  uninitialized constant FriendshipController
# /home/maelfosso/.rvm/gems/ruby-2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/active_support.rb:80:in `block in load_missing_constant'
# /home/maelfosso/.rvm/gems/ruby-2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/active_support.rb:9:in `without_bootsnap_cache'
# /home/maelfosso/.rvm/gems/ruby-2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/active_support.rb:80:in `rescue in load_missing_constant'
# /home/maelfosso/.rvm/gems/ruby-2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/active_support.rb:59:in `load_missing_constant'
# ./spec/controllers/friendship_controller_spec.rb:3:in `<top (required)>'
# ------------------
# --- Caused by: ---
# NameError:
#   uninitialized constant FriendshipController
```

2- Kindly remove all the comments in your code like this one https://github.com/keddo/ror-social-scaffold/blob/dcee12f17dcf5e52bcd195fb762e8ca9158068a9/spec/helpers/friendship_helper_spec.rb#L6-L12 or this one https://github.com/keddo/ror-social-scaffold/blob/dcee12f17dcf5e52bcd195fb762e8ca9158068a9/app/controllers/posts_controller.rb#L23

3- Kindly write integrations tests, please, mostly for the friendship feature

4- Kindly remove logic from views. Like this one
https://github.com/keddo/ror-social-scaffold/blob/dcee12f17dcf5e52bcd195fb762e8ca9158068a9/app/views/users/index.html.erb#L12-L71
Implement that logic (if/else sequence) in view helpers, please

Kindly make the suggested changes and submit a new code review request
Thanks

Mael FOSSO

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello Team
### You have done well so far :clap: However, you have a few issues to fix:-
- [x] The unit tests are failing, kindly solve the issues
- [x] Rubocop is detecting some errors, kindly fix them
- [x] Stylelint also detects errors, install all the required dependencies and run the stylelint command. [Follow this guide](https://github.com/microverseinc/linters-config/tree/master/ror)
### Make the changes and submit for another code review. Good luck.
- Happy coding!

**Review by maelfosso — CHANGES_REQUESTED** [review]
# Changes required :red_circle: 

Hello,

Thank you for making the suggested changes
However, there are an issue

1- What you wrote are controller/request tests instead integration tests as required. Kindly read those articles to know more about integrations tests

- https://coderwall.com/p/thonea/integration-testing-with-rspec-and-devise

- https://www.microverse.org/blog/understanding-rspec-controller-request-specs-integration-test-using-capybara

Kindly write integration tests and submit a new code review request
Thanks

Mael FOSSO

**Review by MarioDena — CHANGES_REQUESTED** [review]
Hello! Great work Implementing the requested changes! 🥇  however we need some details before approving.

# Changes Required 🔴 

- [x] There are not Linter results showing on your PR be sure to set up your linters correctly/avoid editing config files.

- [x] Also be sure to test your project and that all your test are passing

- [x] Remember to double check that your project continues to work as intended after changes are made.

After making the requested changes please re-submit your project for another review.

Cheers! 👍 

Code review by Mario Enrique Delgado Naranjo.

**Review by rOluochKe — APPROVED** [review]
Hello Team
### Well done, you got it right :clap: The project has been approved. Congratulations :boom: :100:
### Merge and submit the project. Good luck with the next one.
- Happy coding!

**Pull request merged**
