### PR TITLE
Code Review - Milestone: Friendships v1

### PR DESCRIPTION
**Pull request by fdfragoso**
- Created the model with associations and all requested features for friendships;
- Create unit and integration tests.

Waiting for code review!

### CODE REVIEW

**Review by trekab — CHANGES_REQUESTED** [review]
### Changes Required! :recycle: 
Hi team! The effort you have put in to write tests is very commendable. :+1:  However, there are several requirements for this milestone that you need to implement before moving forward. These include:
- [x] The user can invite friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/send_invitation.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [x] The user should see friendships requests ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/pending_request.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [x] The user has to accept friendship request to start friendship ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [x] The user can reject a friendship request ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [x] There should be a button to invite a user to friendship on the users' list page and on a single user show page ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/user_can_see_invite_buttton.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [x] The Posts timeline should include posts written by logged-in user and their friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [x] Your linting isn't working for your PR. Consider checking it out. Probably reconfiguring it will help you catch the fault in the setup.

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink: 
__Treasure Kabareebe__
[GitHub](https://github.com/trekab) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

**Review by elmejdki — CHANGES_REQUESTED** [review]
# status: require changes :recycle: 
## Hi, guys well done, you did a great job :clap: :clap: :clap:, but you still need to work :hammer: :wrench: more on this project to get it approved :checkered_flag:.

- [x] There should be a button to invite a user to friendship on the users' list page and on a single user show page (screenshot from Pathwright).

- [x] Friend Requests should not show all the users, it's should show only requests that are coming from other people.

- [x] I tried to reject the friend request but it's not working.

- [x] when clicking on unfriend I got this error:
image

- [ ] Your linting isn't working for your PR. Consider checking it out. Probably reconfiguring it will help you catch the fault in the setup.

### Please make all the required changes before you submit another code review.
## Happy Coding :tophat:

**Review by elmejdki — CHANGES_REQUESTED** [review]
# status: require changes :recycle: 
## Hi, it's me again guys :wave: :wave: :wave:, you are almost there you need just to work on some minor changes.

- [x] as I mentioned before the user show page should show an add friend button or remove friend button.

- [x] rejecting a friendship generate the following error:
image

### please make all the required changes before you submit another code review and test you project also.
## Happy Coding :tophat:

**Comment by keddo** [comment]
- A user show page display the user posts how is it possible to add/remove a friend

**Review by Dandush03 — APPROVED** [review]
# Status: :rocket: Project Approved :rocket: 

### Great Work! Keep It Up :muscle: 

# Happy Coding! :nerd_face: :computer:

**Pull request merged**
